### ISSUE TITLE
Make TranslationCredit appear the same way as contributors

### ISSUE THREAD

**Issue by scootergrisen** [downpoured/scite-files#14]
I suggest changing the translators string and instructor comment as to how to translate the string in the about dialog so each translator name can be found on they own line.

Just like the contributors lines in the about dialog.
So they appear the same way.

In "da" translation file i have written:

```
TranslationCredit=Dansk oversættelse af:\n    Stefan "CyberZed" Poulsen\n    scootergrisen
```

Its properly not the best way with the 4 x space, but maybe someone can find a better way.

**Comment by downpoured** [comment]
I'm about to travel to Idaho until the 17th, I may not have internet connection during this time, but I will look into this issue when I return.

**Comment by downpoured** [comment]
It's a good idea to put contributors on different lines, because having one long line is a bit cumbersome.

There is still a bit of extra typing, but I think using backslash-escaped newlines would be a good approach,
like this,

```
TranslationCredit=\
Dansk oversættelse af:\n\
    Stefan "CyberZed" Poulsen\n\
    scootergrisen
```

I've confirmed that this approach works for me in recent SciTE builds.

**Comment by scootergrisen** [comment]
Yes but i would like comment added to the translations files so all the translations can know the correct way to write it.
I dont think its smart that translators have to start each line with 4 spaces or even use newlines.
Maybe it would be better that the translators only use comma seperated list and then in your code you can spilt the list and add the spaces and newlines.

So in the locale.da.properties file it could say:

    TranslationCreditTitle=Dansk oversættelse af:
    TranslationCreditNames=Stefan "CyberZed" Poulsen,scootergrisen

And with your code it gets turned into this in the about dialog:

    Dansk oversættelse af:
        Stefan "CyberZed" Poulsen
        scootergrisen

That way you can always change the 4 spaces at a later if you want to use tabs or what ever without having to change the locale.*.properties files.

**Comment by downpoured** [comment]
Neil might be open to a patch for this change, but most other properties don't work this way. IIRC, the properties that take a list use | to delimit instead of a comma.

I went through and changed every translation, moving TranslationCredit to the top and splitting long lines into multiple lines, it's true that it is more readable than having one long line with all names.
