### ISSUE TITLE
Latest locale.properties link is not the latest source translation

### ISSUE THREAD

**Issue by scootergrisen** [downpoured/scite-files#19]
On https://github.com/downpoured/scite-files/blob/master/files/translations.md there is a link for the latest translation supposedly but it does not seem to be the latest.

 If i download Release 3.7.1 from http://www.scintilla.org/ScintillaDownload.html i see #3.7.1 at the bottom of scite/win32/locale.properties.

Please make it easy for translators to find the latest source translation so they can update.
And how come there are both locale.properties and locale.en.properties? Should there not just be one or the other?

**Comment by downpoured** [comment]
You're right, Neil's locale.properties on scintilla.org was out of date, I had assumed it would always be the latest. Thank you for opening the issue.

I contacted Neil yesterday on the mailing list and he fixed the problem.

I also updated translations.md to clarify that the latest version with text changes is 3.7.5.

I deleted everything in locale.en.properties, because it's not necessary, and added a comment pointing to the latest locale.properties.
