### ISSUE TITLE
Improve "Microsoft SQL" mssql.proprerties file

### ISSUE THREAD

**Issue by crisistotal2014** [downpoured/scite-files#33]
Hi!
To improve "Microsoft SQL" mssql.proprerties file (and to not replace sql.properties), can be modified header from:

filter.mssql=SQL (sql)|*.sql|
file.patterns.mssql=*.sql
lexer.$(file.patterns.mssql)=mssql

to:

file.patterns.mssql=*.mssql;*.sql
filter.mssql=MS SQL (mssql sql)|$(file.patterns.mssql)|
*filter.mssql=$(filter.mssql)
lexer.$(file.patterns.mssql)=mssql
*language.mssql=MS SQL|spec||

By this way a new lexer will be registered and can live with normal sql.properties file.

Thanks so much!

**Comment by downpoured** [comment]
Checked into
https://github.com/downpoured/scite-files/commit/96cdc664fb5dee0b79a3beb2a0bd960cd45a017a

It looks like some of the * symbols you wrote got eaten by GitHub's formatter, so please confirm that what I added is right. For future reference, you can surround everything by a backtic ` so that * symbols still show up.
